spring.application.name=LibTrack
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5433}/mtgmanager
spring.datasource.username=postgres
spring.datasource.password=root
spring.flyway.locations=classpath:db/migration
api.secret.token.secret=${JWT_SECRET:my-secret-key}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.time-zone=America/Sao_Paulo

spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=b629c00aa8935d
spring.mail.password=f7bab9279a8bf0
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true